# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'Couri' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Couri

  target 'CouriTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CouriUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'FirebaseUI'

end
